export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  HELPDESK = 'ROLE_HELPDESK' ,
  COLLABORATEUR = 'ROLE_COLLABORATEUR' ,
  DEMANDE_CONGE = 'ROLE_DEMANDE_CONGE' ,
  DEMANDE_MISSION = 'ROLE_DEMANDE_MISSION' ,
  DECLARATION_FRAIS = 'ROLE_DECLARATION_FRAIS' ,
  VALIDATEUR = 'ROLE_LIST_COL' ,
  SUIVI_POINT = 'ROLE_SUIVI_POINT' ,
  LIST_COL = 'ROLE_LIST_COL' ,
  RECLAMATION_POINTAGE = 'ROLE_RECLAMATION_POINTAGE' ,
  BILLET_FAVEUR = 'ROLE_BILLET_FAVEUR' ,
  ANNULATION_AVANCE = 'ROLE_ANNULATION_AVANCE' ,
  AVANCE_SALAIRE = 'ROLE_AVANCE_SALAIRE' ,
  DEMANDE_PRET = 'ROLE_DEMANDE_PRET' ,
  FICHE_PAIE = 'ROLE_FICHE_PAIE' ,
  ATTEST_SALAIRE = 'ROLE_ATTEST_SALAIRE' ,
  OVERTIME = 'ROLE_OVERTIME' ,


  TEST = 'ROLE_TEST'
}
